version: '3.8'

services:
  autoclicker_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoclicker_bot_container
    # env_file: .env # Эта строка нужна, если файл называется не .env или находится в другом месте
    # Если файл называется .env и находится в той же директории, Docker Compose подхватит его автоматически.
    # Для явного указания и чтобы быть уверенным, можно раскомментировать строку выше.
    # Однако, по умолчанию Docker Compose ищет файл .env в директории проекта.
    
    # Если нужно передавать переменные окружения напрямую (альтернатива .env файлу, менее предпочтительно для секретов)
    # environment:
    #   - MISTRAL_API_KEY=${MISTRAL_API_KEY} # Берет значение из твоего локального окружения или .env файла

    # Добавь сюда другие необходимые настройки, например, тома для сохранения файлов,
    # если subscribers.txt или скриншоты должны сохраняться между перезапусками контейнера.
    # volumes:
    #   - ./app:/app/app # Пример монтирования директории app для разработки
    #   - ./subscribers.txt:/app/subscribers.txt # Пример монтирования файла
    #   - ./debug_screenshots:/app # Пример монтирования папки для скриншотов (если они сохраняются в /app)

    # Убедись, что у контейнера есть доступ к X-серверу для pyautogui, если он запускается не в headless режиме
    # Это может потребовать дополнительных настроек в зависимости от твоей системы.
    # Для работы GUI в Docker часто используют Xvfb, который у тебя уже установлен в Dockerfile.
    # Команда CMD ["/app/start.sh"] в Dockerfile должна это учитывать.
    
    # Если твой start.sh ожидает интерактивный терминал:
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
